# Generated by Django 3.0.2 on 2020-01-10 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_startDate', models.DateField()),
                ('staff_position', models.CharField(blank=True, max_length=200)),
                ('staff_salary', models.DecimalField(blank=True, decimal_places=3, max_digits=13)),
                ('staff_hospital_list', models.ManyToManyField(blank=True, to='stratHealthApp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=300)),
                ('procedure_description', models.CharField(blank=True, max_length=1000)),
                ('procedure_date', models.DateTimeField()),
                ('procedure_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=16)),
                ('procedure_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stratHealthApp.ProcedureCategory')),
                ('procedure_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratHealthApp.Hospital')),
                ('procedure_staff_list', models.ManyToManyField(blank=True, to='stratHealthApp.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_hospitalgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratHealthApp.HospitalGroup'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_address', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=200)),
                ('contact_position', models.CharField(blank=True, max_length=200)),
                ('contact_hospital_list', models.ManyToManyField(blank=True, to='stratHealthApp.Hospital')),
            ],
        ),
    ]
